[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["oakveil-update", "mods", "server"]

[package]
namespace = "Kindred"
name = "KinThrone"
versionNumber = "1.1.0"
description = "Harness the true power of the shadow realm!"
websiteUrl = "https://github.com/mfoltz/KinThrone"
containsNsfwContent = false
