[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["1-0-update", "mods", "server"]

[package]
namespace = "Kindred"
name = "KinThrone"
versionNumber = "1.0.0"
description = "Send servants on missions from the Throne of Darkness!"
websiteUrl = "https://github.com/mfoltz/KinThrone"
containsNsfwContent = false
