[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["1-0-update", "mods", "server"]

[package]
namespace = "Kindred"
name = "KinThrone"
versionNumber = "1.1.0"
description = "Harness the power of the shadow realm!"
websiteUrl = "https://github.com/mfoltz/KinThrone"
containsNsfwContent = false
